var headerText='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum luctus lacus, quis venenatis ex condimentum vitae. Morbi elementum ipsum diam, ut sodales elit interdum quis. Nulla nunc ipsum, pretium ac ultrices id, faucibus vitae urna. Vivamus tortor ex, mattis et porta et, interdum vel justo. Sed dictum consequat faucibus. Praesent et massa euismod, congue mi et, pulvinar mauris. Nulla consectetur ornare ante, sed pellentesque velit accumsan at. In rhoncus est tortor, nec euismod erat consectetur in. Phasellus volutpat eu enim venenatis ultrices. Curabitur ut turpis diam. Sed at ultrices tellus. Quisque interdum neque quis massa varius tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam a tellus arcu. Ut eu nisi convallis, rutrum mauris non, aliquet magna. Vivamus aliquet nisl ut arcu rhoncus, nec faucibus nulla sodales.'
var footerText='Etiam eleifend turpis tortor, et condimentum velit vulputate in. Ut malesuada diam sit amet eleifend malesuada. Nulla tristique dui a iaculis viverra. Sed quis varius nisl. Morbi ut sagittis mauris. Curabitur vel neque odio. Vestibulum suscipit imperdiet feugiat. In gravida lectus a rhoncus consequat. Quisque a lectus vel mauris pretium molestie vitae ac felis. Donec vel magna dictum, eleifend mauris eget, facilisis ante. Donec mattis imperdiet orci sit amet molestie.'
var buttonsDescriptions = [
    'Donec dapibus cursus leo, a faucibus turpis. Duis et laoreet lacus, eu imperdiet magna. Pellentesque porttitor mauris et imperdiet gravida. Praesent sodales venenatis nibh mollis ultrices. Phasellus maximus ante orci, ac posuere ex pharetra vitae. Quisque cursus nibh neque, non placerat lacus aliquam sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dictum pretium metus at imperdiet. Sed fringilla odio facilisis risus ultrices porttitor. Proin volutpat vestibulum est.',

    'Duis faucibus, augue ac sollicitudin tempor, erat nunc eleifend sapien, sed eleifend risus risus malesuada arcu. Integer tempor ex arcu, in mattis orci dictum sit amet. Proin finibus tellus nec consequat placerat. Curabitur urna turpis, semper eget felis vitae, hendrerit tristique libero. Suspendisse et vestibulum justo, sit amet viverra sem. Curabitur egestas quis justo sed dictum. Nullam mollis, nunc a maximus porta, enim tortor imperdiet diam, at ornare sem felis in tortor. Maecenas euismod at est et vehicula. Cras ac ullamcorper mauris. ',
    'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque aliquet dignissim enim. Vestibulum vestibulum feugiat augue. Phasellus metus magna, pulvinar eget nibh id, semper pulvinar nisl. Nulla sed laoreet turpis. Sed a metus nec massa auctor fermentum eget a nibh. Nullam at dolor lorem. Donec vitae velit nulla. Praesent egestas vulputate imperdiet. Integer eu molestie arcu. Suspendisse potenti. Aenean vitae magna ullamcorper, finibus augue nec, aliquet odio. Cras sit amet euismod risus. Pellentesque a enim lectus.',
    'Curabitur accumsan felis ligula, sit amet scelerisque arcu interdum at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce mattis, dui eleifend congue tincidunt, odio dolor imperdiet metus, quis mollis neque mauris vitae felis. Mauris sed pulvinar metus. Nunc odio est, sodales in est sed, mollis egestas mauris. Cras turpis nisi, mollis volutpat vestibulum auctor, tristique commodo lectus. Ut fermentum nulla luctus, ornare tortor nec, bibendum dui. Nunc facilisis mollis ultrices. Praesent vel luctus nulla, quis faucibus leo. ',

    'In ac hendrerit nisi. Nam ex elit, tincidunt nec bibendum ac, iaculis eu metus. Etiam mattis, turpis eu tincidunt maximus, dolor purus commodo nunc, in pharetra velit libero sit amet tellus. Duis tempus, erat id maximus commodo, sapien tortor sodales lorem, ut dictum ex orci ut magna. Vivamus hendrerit nulla ligula, a molestie ex eleifend sed. Integer ut risus imperdiet, bibendum arcu ac, venenatis nulla. Nam cursus lorem sed odio commodo, ac faucibus nisi posuere. Pellentesque ut sagittis ligula. Maecenas quis volutpat nibh, sit amet laoreet dui.',
    'Curabitur interdum rhoncus nulla eget ornare. Vestibulum ut libero ornare, ultrices metus ut, tristique metus. Sed erat libero, suscipit sit amet dui at, finibus pulvinar dolor. Duis odio nisi, fringilla elementum odio vitae, consequat accumsan eros. Nam et metus laoreet nunc vulputate sollicitudin. Curabitur faucibus nibh vel blandit laoreet. Nulla facilisi. Maecenas in diam et nunc pretium porta. Phasellus purus orci, maximus vitae nisi quis, dignissim dapibus augue. Nulla semper mattis sollicitudin. Integer lobortis nisl dui, eget accumsan sapien commodo at.',
    'Integer eu gravida nulla, non mollis eros. Integer luctus eget massa sed lobortis. Sed sodales purus non eros sodales, sit amet tincidunt lacus tempus. Sed augue nunc, eleifend id nisi eget, gravida bibendum quam. Pellentesque nec facilisis nibh, non semper urna. Integer vel felis a augue accumsan tincidunt. Vivamus lacinia feugiat libero id mattis. Aliquam lobortis, massa non pretium efficitur, elit massa vehicula elit, sed venenatis tellus felis sed nibh. Mauris efficitur orci eu tortor mattis malesuada.',

    'Nulla vitae rutrum eros. Nam commodo cursus mauris ut porta. Nam sagittis urna a pharetra ornare. In et volutpat risus, non sagittis eros. Maecenas id vulputate turpis. Aenean pulvinar dui et pharetra porta. Fusce eu massa ut augue pulvinar facilisis. Etiam malesuada sapien sed elementum eleifend. Morbi gravida, libero a posuere vestibulum, lectus neque laoreet mi, in cursus dolor nisi sed lorem. Etiam vitae velit semper, commodo dui eget, porttitor eros. Ut pretium rutrum varius.',
    'Mollis elementum est ac malesuada. Fusce efficitur mattis lacinia. Aenean nibh orci, finibus ut sem in, sollicitudin iaculis nisi. Curabitur at felis pellentesque, dignissim urna malesuada, accumsan velit. Nam turpis turpis, posuere eu velit ultricies, tincidunt suscipit erat. Suspendisse viverra mauris varius, gravida magna vitae, cursus nisl. Integer egestas purus ac tortor tempor, ut lacinia ante mattis. Vestibulum euismod maximus felis. Donec eget tellus eu erat eleifend fringilla ut in purus.',
    'Suspendisse non efficitur mauris. Quisque vestibulum quis erat ut ullamcorper. Ut facilisis nulla massa, nec venenatis lectus ultricies id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut turpis iaculis, iaculis risus non, interdum magna. Vivamus id iaculis mi. Nunc dapibus malesuada urna, at porttitor leo sagittis a. Phasellus et viverra elit. Suspendisse viverra accumsan bibendum.',
    
];
var smallText='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum luctus lacus, quis venenatis ex condimentum vitae. Morbi elementum ipsum diam, ut sodales elit interdum quis. Nulla nunc ipsum, pretium ac ultrices id, faucibus vitae urna. Vivamus tortor ex, mattis et porta et, interdum vel justo. Sed dictum consequat faucibus. Praesent et massa euismod, congue mi et, pulvinar mauris. Nulla consectetur ornare ante, sed pellentesque velit accumsan at. Dolorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum euismod maximus felis. Donec eget tellus eu erat eleifend fringilla ut in purus.'
export default {headerText,footerText,buttonsDescriptions,smallText}